# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Core Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name to re-build ?
        required: true
        type: string

  push:
    paths:
      - 'node/**'
      - '.github/workflows/**'

jobs:
  build:
    env:
      branch: ${{ inputs.branch || github.ref_name }}
      stage: ${{ inputs.branch == 'main' && 'latest' || github.ref_name == 'main' && 'latest' || 'next' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dont-code/core
          path: core
          fetch-depth: 0
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: core/node/package-lock.json
      - name: Install
        run: |
          npm install -g nx
          npm ci
        working-directory: 'core/node'
      - name: Build
        run: |
          nx run core:build:development
          nx run core:test
        working-directory: 'core/node'
