# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Patch release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release, if needed (x.y.z)
        required: false
        type: string
      next:
        description: Is it a next release ?
        required: true
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dont-code/core
          path: core
          fetch-depth: 0
          ref: 'main'
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: core/node/package-lock.json
      - name: Version
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.version == '') }}
        run: |
          PACKAGE_VERSION=$(npm view @dontcode/core versions --json | jq -r '.[-1]')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          npm version $PACKAGE_VERSION
        working-directory: 'core/node/packages/core'
      - name: Version Next
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.version == '') && ( inputs.next == true) }}
        run: |
          npm version patch
        working-directory: 'core/node/packages/core'
      - name: Version Patch
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.version == '') && ( inputs.next == false) }}
        run: |
          npm version patch
        working-directory: 'core/node/packages/core'
      - name: Version Set
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.version != '') }}
        run: |
          PACKAGE_VERSION=${{inputs.version}}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          npm version $PACKAGE_VERSION
        working-directory: 'core/node/packages/core'
      - name: Install
        run: |
          npm install -g nx
          npm install --force
        working-directory: 'core/node'
      - name: Build and Test
        run: |
          nx run core:build:production
          nx run core:test
        working-directory: 'core/node'
      - name: Publish
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.next == true) }}
        run: |
          npm publish core/node/dist/packages/core --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        if: ${{ success() && ( matrix.browser == 'chromium' ) && ( inputs.next == false) }}
        run: |
          npm publish core/node/dist/packages/core --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
