# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: node

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm ci
      - name: Install
        run: git merge Development
      - name: Build
        run: npm version patch
      - name: Build
        run: npm run nx run core:build
      #      - uses: actions/upload-artifact@v1
      #        with:
      #          name: distribution
      #          path: node/dist/libs/core
      - name: Unit tests
        run: npm run nx run core:test
      - name: Push
        run: git push
      - name: Publish
        run: npm publish dist/libs/core --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
